# Configuraci\u00f3n del puerto del servidor (para que no choque con Angular)
server.port=8080

# Conexi\u00f3n a la Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/incidentes_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456789

# Configuraci\u00f3n de Hibernate (Manejo de tablas)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true